services:
  mysql:
    image: mysql:8.0
    container_name: subasta-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: subasta_db
      MYSQL_USER: subasta_user
      MYSQL_PASSWORD: subasta_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --server-id=1 --log-bin=mysql-bin --binlog-format=ROW --binlog-row-image=FULL

volumes:
  mysql_data: