spring:
  application:
    name: subasta-api

  datasource:
    url: jdbc:mysql://localhost:3306/subasta_db
    username: subasta_user
    password: subasta_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  kafka:
    bootstrap-servers: localhost:19092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

server:
  port: 8080

jwt:
  secret: "Z40J.dJc2-xw}Xw|$$5sb/O2#1M^.<7NUi3+!Q@(bvW"
  expiration: 900 # 15 minutos en segundos